within TwoTanksExample.VerificationModels;

model verif_model_autogen_2 "Autogenerated verification model"
  extends VVDRlib.Verification.VerificationModel;
  TwoTanksExample.Requirements.Volume_of_a_tank _agen_Volume_of_a_tank6_autogen_bind_0(tankVolume = _agen_TwoTanksDesign1.tank2.volume);
  TwoTanksExample.Requirements.Volume_of_a_tank _agen_Volume_of_a_tank6_autogen_bind_1(tankVolume = _agen_TwoTanksDesign1.tank1.volume);
  TwoTanksExample.Requirements.LiquidLevel _agen_LiquidLevel5_autogen_bind_0(waterLevel = _agen_TwoTanksDesign1.tank2.levelOfLiquid);
  TwoTanksExample.Requirements.LiquidLevel _agen_LiquidLevel5_autogen_bind_1(waterLevel = _agen_TwoTanksDesign1.tank1.levelOfLiquid);
  TwoTanksExample.Requirements.LevelAdjustment _agen_LevelAdjustment4_autogen_bind_0(inFlow = _agen_TwoTanksDesign1.tank2.levelOfLiquid);
  TwoTanksExample.Requirements.LevelAdjustment _agen_LevelAdjustment4_autogen_bind_1(inFlow = _agen_TwoTanksDesign1.tank1.levelOfLiquid);
  TwoTanksExample.Requirements.DrainTime _agen_DrainTime3;
  TwoTanksExample.Requirements.NewReq _agen_NewReq2;
  TwoTanksExample.Design.TwoTanksDesign _agen_TwoTanksDesign1(source.flowLevel = _agen_Overflow0.flowLevel);
  TwoTanksExample.Scenarios.Overflow _agen_Overflow0;
end verif_model_autogen_2;